---
- hosts: gbm-live
  remote_user: root

  tasks:
    # user-related actions
    - name: Create non-root account
      user:
        name: gbm
        comment: "Grand Bargain Monitoring Account"
        createhome: yes

    # software installation
    - name: Update apt caches
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install python 3
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python-pip
        state: present

    - name: Install virtualenv
      apt:
        name: virtualenv
        state: present

    - name: Install apache
      apt:
        name: apache2
        state: present

    - name: Install apache/python3 depenencies
      apt:
        name: libapache2-mod-wsgi-py3
        state: present

    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present
